---
abstract: 'Role for event emitting classes'
author:
  - 'Doug Bell <preaction@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::Compile: 0
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Beam-Emitter
requires:
  Moo: 0
  MooX::Types::MooseLike: 0
resources:
  bugtracker: https://github.com/preaction/Beam-Emitter/issues
  homepage: https://github.com/preaction/Beam-Emitter
  repository: https://github.com/preaction/Beam-Emitter.git
version: 0.002
