---
abstract: 'Role for event emitting classes'
author:
  - 'Doug Bell <preaction@cpan.org>'
build_requires:
  Module::Build: '0.28'
  Test::Compile: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.023, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Beam-Emitter
requires:
  Carp: '0'
  Moo: '0'
  Scalar::Util: '0'
  Types::Standard: '0.008'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/preaction/Beam-Emitter/issues
  homepage: https://github.com/preaction/Beam-Emitter
  repository: https://github.com/preaction/Beam-Emitter.git
version: '0.004'
x_authority: cpan:PREACTION
x_contributors:
  - 'Joel Berger <joel.a.berger@gmail.com>'
